name: "Rust CI setup"
description: "Sets up Rust toolchain, sccache and CI tools (composite action)."

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Rust toolchain (stable) + components
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
        components: clippy, rustfmt

    - name: Ensure sccache dir + env
      shell: bash
      run: |
        echo "CARGO_TERM_COLOR=always" >> $GITHUB_ENV
        echo "SCCACHE_DIR=$HOME/.cache/sccache" >> $GITHUB_ENV
        echo "SCCACHE_CACHE_SIZE=10G" >> $GITHUB_ENV

    - name: Install cargo-binstall (fast binary installer)
      shell: bash
      run: |
        if ! command -v cargo-binstall >/dev/null 2>&1; then
          curl -LsSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall.sh | bash
        fi

    - name: Install CI tools (sccache, cargo-chef, cargo-audit)
      shell: bash
      run: |
        # try binstall first (faster). Fallback to cargo install when necessary.
        if command -v cargo-binstall >/dev/null 2>&1; then
          cargo binstall -y sccache || true
          cargo binstall -y cargo-chef || true
          cargo binstall -y cargo-audit || true
        fi
        # fallback installs 
        command -v sccache >/dev/null 2>&1 || cargo install --locked sccache
        command -v cargo-chef >/dev/null 2>&1 || cargo install --locked cargo-chef
        command -v cargo-audit >/dev/null 2>&1 || cargo install --locked cargo-audit

    - name: Ensure RUSTC_WRAPPER points to sccache (if available)
      shell: bash
      run: |
        if command -v sccache >/dev/null 2>&1; then
          echo "RUSTC_WRAPPER=$(which sccache)" >> $GITHUB_ENV
        fi